[versions]
assertj = "3.27.6"
errorprone = "2.45.0"
errorprone-plugin = "4.3.0"
mockito-junit = "5.21.0"
nullaway = "0.12.14"
palantir-java-format = "2.73.0"
quarkus = "3.30.5"
quarkus-quinoa = "2.7.1"
rest-assured = "6.0.0"
testcontainers = "1.21.4"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-junit" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
quarkus-elytron-security = { module = "io.quarkus:quarkus-elytron-security", version.ref = "quarkus" }
quarkus-flyway = { module = "io.quarkus:quarkus-flyway", version.ref = "quarkus" }
quarkus-hibernate-orm-panache = { module = "io.quarkus:quarkus-hibernate-orm-panache", version.ref = "quarkus" }
quarkus-hibernate-validator = { module = "io.quarkus:quarkus-hibernate-validator", version.ref = "quarkus" }
quarkus-jdbc-postgresql = { module = "io.quarkus:quarkus-jdbc-postgresql", version.ref = "quarkus" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5", version.ref = "quarkus" }
quarkus-quinoa = { module = "io.quarkiverse.quinoa:quarkus-quinoa", version.ref = "quarkus-quinoa" }
quarkus-rest = { module = "io.quarkus:quarkus-rest", version.ref = "quarkus" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkus" }
quarkus-smallrye-jwt = { group = "io.quarkus", name = "quarkus-smallrye-jwt", version.ref = "quarkus" }
restassured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }