version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    assignees:
      - "Breus"
      - "EmielBoss"
    reviewers:
      - "Breus"
      - "EmielBoss"
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "quarterly"
    assignees:
      - "Breus"
      - "EmielBoss"
    reviewers:
      - "Breus"
      - "EmielBoss"
    groups:
      dependencies-backend-production:
        dependency-type: "production"
        patterns: ["*"]
      dependencies-backend-development:
        dependency-type: "development"
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "quarterly"
    assignees:
      - "Breus"
      - "EmielBoss"
    reviewers:
      - "Breus"
      - "EmielBoss"
    groups:
      dependencies-frontend-production:
        dependency-type: "production"
        patterns: ["*"]
      dependencies-frontend-development:
        dependency-type: "development"
        patterns: ["*"]