version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "quarterly"
    groups:
      dependencies-backend-production:
        dependency-type: "production"
        applies-to: version-updates
        applies-to: security-updates
        patterns: ["*"]
      dependencies-backend-development:
        dependency-type: "development"
        applies-to: version-updates
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "quarterly"
    groups:
      dependencies-frontend-production:
        dependency-type: "production"
        applies-to: version-updates
        applies-to: security-updates
        patterns: ["*"]
      dependencies-frontend-development:
        dependency-type: "development"
        applies-to: version-updates
        applies-to: security-updates
        patterns: ["*"]