# This file is used for local development only
services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: recipe_book
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  garage:
    image: dxflrs/garage:v2.1.0
    ports:
      - "3900:3900" # S3 API
      - "3901:3901" # RPC
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  quarkus:
    build:
      context: ./app
      dockerfile: ./src/main/docker/Dockerfile.jvm
    environment:
      POSTGRES_PASSWORD: localdevpassword
      PUB_KEY_LOCATION: classpath:local-dev-keys/publicKey.pem
      PRIV_KEY_LOCATION: classpath:local-dev-keys/privateKey.pem
    ports:
      - "8081:8081"

volumes:
  pg_data:
  garage_meta:
  garage_data: